http
{
	server
	{
		listen 3091;
		error_page index.html;
	}
	server
	{
		listen 10.11.1.1:2000;
	}
	server
	{
		listen 10.11.1.1:2001;
		server_name http://www.example.com;
		server_name http://www.emad.com;
	}
	server
	{
		listen 127.0.0.1:2001;
		server_name http://www.example.com;
	}
}